image: node:22

stages:
  - deploy

pages:
  stage: deploy

  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile

  script:
    - pnpm run build

  artifacts:
    paths:
      - dist

  publish: dist

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'